version: '3'
services:
  ranger-kms:
    build:
      context: .
      dockerfile: Dockerfile.ranger-kms
      args:
        - RANGER_VERSION=${RANGER_VERSION}
        - RANGER_DB_TYPE=${RANGER_DB_TYPE}
    image: ranger-kms:latest
    container_name: ranger-kms
    hostname: ranger-kms.example.com
    stdin_open: true
    tty: true
    networks:
      - ranger
    ports:
      - "9292:9292"
    depends_on:
      ranger:
        condition: service_started
    environment:
      - RANGER_VERSION
      - RANGER_DB_TYPE
    volumes:
      - ./kerberos-files/krb5.conf:/etc/krb5.conf:rw
      - ./kerberos-files/keytabs:/etc/security/keytabs:rw
#    Run the container as root to allow the ownership change.
    user: root
    entrypoint: >
      sh -c "
      chown -R root:root /etc/security/keytabs &&
      /home/ranger/scripts/ranger-kms.sh"
#    command:
#      - /home/ranger/scripts/ranger-kms.sh

networks:
  ranger:
    name: rangernw
