version: '3'
services:
  ranger:
    build:
      context: .
      dockerfile: Dockerfile.ranger
      args:
        - RANGER_VERSION=${RANGER_VERSION}
        - RANGER_DB_TYPE=${RANGER_DB_TYPE}
        - RANGER_ADMIN_JAVA_VERSION=${RANGER_ADMIN_JAVA_VERSION}
    image: ranger:latest
    container_name: ranger
    hostname: ranger.example.com
    stdin_open: true
    tty: true
    networks:
      - ranger
    ports:
      - "6080:6080"
      - "1001:1001"
    depends_on:
      ranger-zk:
        condition: service_started
      ranger-db:
        condition: service_healthy
      ranger-solr:
        condition: service_started
    environment:
      - RANGER_VERSION
      - RANGER_DB_TYPE
      - DEBUG_ADMIN=${DEBUG_ADMIN:-false}
    volumes:
      - ./kerberos-files/krb5.conf:/etc/krb5.conf:rw
      - ./kerberos-files/keytabs:/etc/security/keytabs:rw
#    Run the container as root to allow the ownership change.
    user: root
    entrypoint: >
      sh -c "
      chown -R root:root /etc/security/keytabs &&
      /home/ranger/scripts/ranger.sh"
#    command:
#      - /home/ranger/scripts/ranger.sh

  ranger-zk:
    build:
      context: .
      dockerfile: Dockerfile.ranger-zk
    image: ranger-zk
    container_name: ranger-zk
    hostname: ranger-zk.example.com
    networks:
      - ranger
    ports:
      - "2181:2181"

  ranger-solr:
    build:
      context: .
      dockerfile: Dockerfile.ranger-solr
    image: ranger-solr
    container_name: ranger-solr
    hostname: ranger-solr.example.com
    networks:
      - ranger
    ports:
      - "8983:8983"
    command:
      - solr-precreate
      - ranger_audits
      - /opt/solr/server/solr/configsets/ranger_audits/

networks:
  ranger:
    name: rangernw
